name = "nuxt"
main = "./.output/server/index.mjs"
workers_dev = true
compatibility_date = "2022-09-10"
account_id = "9ba52192e6bf2e5785e83c2ccb0d68ae"
route = { pattern = "nuxt.bank.green", custom_domain = true }

[site]
bucket = ".output/public"
