// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for AccordionItem documents */
interface AccordionitemDocumentData {
    /**
     * Title field in *AccordionItem*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: accordionitem.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Slice Zone field in *AccordionItem*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: accordionitem.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<AccordionitemDocumentDataSlicesSlice>;
}
/**
 * Slice for *AccordionItem → Slice Zone*
 *
 */
type AccordionitemDocumentDataSlicesSlice = ButtonSliceSlice | EmbedSliceSlice | ImageSliceSlice | TextSliceSlice;
/**
 * AccordionItem document from Prismic
 *
 * - **API ID**: `accordionitem`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AccordionitemDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<AccordionitemDocumentData>, "accordionitem", Lang>;
/** Content for BlogPost documents */
interface BlogpostDocumentData {
    /**
     * Title field in *BlogPost*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blogpost.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Author field in *BlogPost*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blogpost.author
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    author: prismicT.KeyTextField;
    /**
     * PublicationDate field in *BlogPost*
     *
     * - **Field Type**: Date
     * - **Placeholder**: *None*
     * - **API ID Path**: blogpost.publicationdate
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/date
     *
     */
    publicationdate: prismicT.DateField;
    /**
     * Description field in *BlogPost*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blogpost.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Slice Zone field in *BlogPost*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: blogpost.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<BlogpostDocumentDataSlicesSlice>;
}
/**
 * Slice for *BlogPost → Slice Zone*
 *
 */
type BlogpostDocumentDataSlicesSlice = ImageSliceSlice | TextSliceSlice | EmbedSliceSlice;
/**
 * BlogPost document from Prismic
 *
 * - **API ID**: `blogpost`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogpostDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<BlogpostDocumentData>, "blogpost", Lang>;
/** Content for ContactPage documents */
interface ContactpageDocumentData {
    /**
     * Description field in *ContactPage*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contactpage.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * ContactPage document from Prismic
 *
 * - **API ID**: `contactpage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactpageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<ContactpageDocumentData>, "contactpage", Lang>;
/** Content for FAQPage documents */
interface FaqpageDocumentData {
    /**
     * Introduction field in *FAQPage*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: faqpage.introduction
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    introduction: prismicT.RichTextField;
    /**
     * Slice Zone field in *FAQPage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: faqpage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<FaqpageDocumentDataSlicesSlice>;
}
/**
 * Slice for *FAQPage → Slice Zone*
 *
 */
type FaqpageDocumentDataSlicesSlice = AccordionSliceSlice;
/**
 * FAQPage document from Prismic
 *
 * - **API ID**: `faqpage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FaqpageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<FaqpageDocumentData>, "faqpage", Lang>;
/** Content for TakeActionPage documents */
interface TakeactionpageDocumentData {
    /**
     * Introduction field in *TakeActionPage*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: takeactionpage.introduction
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    introduction: prismicT.RichTextField;
    /**
     * Slice Zone field in *TakeActionPage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: takeactionpage.slices1[]
     * - **Tab**: Pressure
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices1: prismicT.SliceZone<TakeactionpageDocumentDataSlices1Slice>;
    /**
     * Slice Zone field in *TakeActionPage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: takeactionpage.slices2[]
     * - **Tab**: Switch
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices2: prismicT.SliceZone<TakeactionpageDocumentDataSlices2Slice>;
    /**
     * Slice Zone field in *TakeActionPage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: takeactionpage.slices3[]
     * - **Tab**: Share
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices3: prismicT.SliceZone<TakeactionpageDocumentDataSlices3Slice>;
    /**
     * Slice Zone field in *TakeActionPage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: takeactionpage.slices4[]
     * - **Tab**: Learn
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices4: prismicT.SliceZone<TakeactionpageDocumentDataSlices4Slice>;
}
/**
 * Slice for *TakeActionPage → Slice Zone*
 *
 */
type TakeactionpageDocumentDataSlices1Slice = EmbedSliceSlice | ImageSliceSlice | TextSliceSlice | ButtonSliceSlice | AccordionSliceSlice;
/**
 * Slice for *TakeActionPage → Slice Zone*
 *
 */
type TakeactionpageDocumentDataSlices2Slice = EmbedSliceSlice | ImageSliceSlice | TextSliceSlice | ButtonSliceSlice | AccordionSliceSlice;
/**
 * Slice for *TakeActionPage → Slice Zone*
 *
 */
type TakeactionpageDocumentDataSlices3Slice = EmbedSliceSlice | ImageSliceSlice | TextSliceSlice | ButtonSliceSlice | AccordionSliceSlice | SocialSharerSliceSlice | SharePicGallerySliceSlice;
/**
 * Slice for *TakeActionPage → Slice Zone*
 *
 */
type TakeactionpageDocumentDataSlices4Slice = EmbedSliceSlice | ImageSliceSlice | TextSliceSlice | ButtonSliceSlice | AccordionSliceSlice;
/**
 * TakeActionPage document from Prismic
 *
 * - **API ID**: `takeactionpage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TakeactionpageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<TakeactionpageDocumentData>, "takeactionpage", Lang>;
export type AllDocumentTypes = AccordionitemDocument | BlogpostDocument | ContactpageDocument | FaqpageDocument | TakeactionpageDocument;
/**
 * Primary content in AccordionSlice → Primary
 *
 */
interface AccordionSliceSliceRichTextPrimary {
    /**
     * Title field in *AccordionSlice → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: accordion_slice.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Content field in *AccordionSlice → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: accordion_slice.primary.content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
}
/**
 * Rich Text variation for AccordionSlice Slice
 *
 * - **API ID**: `richText`
 * - **Description**: `AccordionSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AccordionSliceSliceRichText = prismicT.SharedSliceVariation<"richText", Simplify<AccordionSliceSliceRichTextPrimary>, never>;
/**
 * Primary content in AccordionSlice → Primary
 *
 */
interface AccordionSliceSliceRichTextWithStepPrimary {
    /**
     * Title field in *AccordionSlice → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: accordion_slice.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Content field in *AccordionSlice → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: accordion_slice.primary.content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
    /**
     * Step field in *AccordionSlice → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: accordion_slice.primary.step
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    step: prismicT.KeyTextField;
}
/**
 * Rich Text With Step variation for AccordionSlice Slice
 *
 * - **API ID**: `richTextWithStep`
 * - **Description**: `AccordionSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AccordionSliceSliceRichTextWithStep = prismicT.SharedSliceVariation<"richTextWithStep", Simplify<AccordionSliceSliceRichTextWithStepPrimary>, never>;
/**
 * Primary content in AccordionSlice → Primary
 *
 */
interface AccordionSliceSliceDefaultPrimary {
    /**
     * ContentLink field in *AccordionSlice → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: accordion_slice.primary.contentlink
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    contentlink: prismicT.RelationField;
}
/**
 * Content Link variation for AccordionSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `AccordionSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AccordionSliceSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<AccordionSliceSliceDefaultPrimary>, never>;
/**
 * Slice variation for *AccordionSlice*
 *
 */
type AccordionSliceSliceVariation = AccordionSliceSliceRichText | AccordionSliceSliceRichTextWithStep | AccordionSliceSliceDefault;
/**
 * AccordionSlice Shared Slice
 *
 * - **API ID**: `accordion_slice`
 * - **Description**: `AccordionSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AccordionSliceSlice = prismicT.SharedSlice<"accordion_slice", AccordionSliceSliceVariation>;
/**
 * Primary content in ButtonSlice → Primary
 *
 */
interface ButtonSliceSliceDefaultPrimary {
    /**
     * Label field in *ButtonSlice → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: button_slice.primary.label
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    label: prismicT.KeyTextField;
    /**
     * Link field in *ButtonSlice → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: button_slice.primary.link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
}
/**
 * Default variation for ButtonSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ButtonSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ButtonSliceSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ButtonSliceSliceDefaultPrimary>, never>;
/**
 * Slice variation for *ButtonSlice*
 *
 */
type ButtonSliceSliceVariation = ButtonSliceSliceDefault;
/**
 * ButtonSlice Shared Slice
 *
 * - **API ID**: `button_slice`
 * - **Description**: `ButtonSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ButtonSliceSlice = prismicT.SharedSlice<"button_slice", ButtonSliceSliceVariation>;
/**
 * Primary content in EmbedSlice → Primary
 *
 */
interface EmbedSliceSliceDefaultPrimary {
    /**
     * Target field in *EmbedSlice → Primary*
     *
     * - **Field Type**: Embed
     * - **Placeholder**: *None*
     * - **API ID Path**: embed_slice.primary.target
     * - **Documentation**: https://prismic.io/docs/core-concepts/embed
     *
     */
    target: prismicT.EmbedField;
}
/**
 * Default variation for EmbedSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `VideoBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type EmbedSliceSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<EmbedSliceSliceDefaultPrimary>, never>;
/**
 * Slice variation for *EmbedSlice*
 *
 */
type EmbedSliceSliceVariation = EmbedSliceSliceDefault;
/**
 * EmbedSlice Shared Slice
 *
 * - **API ID**: `embed_slice`
 * - **Description**: `VideoBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type EmbedSliceSlice = prismicT.SharedSlice<"embed_slice", EmbedSliceSliceVariation>;
/**
 * Primary content in ImageSlice → Primary
 *
 */
interface ImageSliceSliceDefaultPrimary {
    /**
     * Image field in *ImageSlice → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: image_slice.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * Caption field in *ImageSlice → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: image_slice.primary.caption
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    caption: prismicT.RichTextField;
}
/**
 * Default variation for ImageSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `BlogImage`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageSliceSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ImageSliceSliceDefaultPrimary>, never>;
/**
 * Slice variation for *ImageSlice*
 *
 */
type ImageSliceSliceVariation = ImageSliceSliceDefault;
/**
 * ImageSlice Shared Slice
 *
 * - **API ID**: `image_slice`
 * - **Description**: `BlogImage`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageSliceSlice = prismicT.SharedSlice<"image_slice", ImageSliceSliceVariation>;
/**
 * Default variation for SharePicGallerySlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `SharePicGallerySlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SharePicGallerySliceSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, never>;
/**
 * Slice variation for *SharePicGallerySlice*
 *
 */
type SharePicGallerySliceSliceVariation = SharePicGallerySliceSliceDefault;
/**
 * SharePicGallerySlice Shared Slice
 *
 * - **API ID**: `share_pic_gallery_slice`
 * - **Description**: `SharePicGallerySlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SharePicGallerySliceSlice = prismicT.SharedSlice<"share_pic_gallery_slice", SharePicGallerySliceSliceVariation>;
/**
 * Default variation for SocialSharerSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `SocialSharerSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SocialSharerSliceSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, never>;
/**
 * Slice variation for *SocialSharerSlice*
 *
 */
type SocialSharerSliceSliceVariation = SocialSharerSliceSliceDefault;
/**
 * SocialSharerSlice Shared Slice
 *
 * - **API ID**: `social_sharer_slice`
 * - **Description**: `SocialSharerSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SocialSharerSliceSlice = prismicT.SharedSlice<"social_sharer_slice", SocialSharerSliceSliceVariation>;
/**
 * Primary content in TextSlice → Primary
 *
 */
interface TextSliceSliceDefaultPrimary {
    /**
     * Text field in *TextSlice → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: text_slice.primary.text
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    text: prismicT.RichTextField;
}
/**
 * Default variation for TextSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `TextSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextSliceSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<TextSliceSliceDefaultPrimary>, never>;
/**
 * Slice variation for *TextSlice*
 *
 */
type TextSliceSliceVariation = TextSliceSliceDefault;
/**
 * TextSlice Shared Slice
 *
 * - **API ID**: `text_slice`
 * - **Description**: `TextSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextSliceSlice = prismicT.SharedSlice<"text_slice", TextSliceSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { AccordionitemDocumentData, AccordionitemDocumentDataSlicesSlice, AccordionitemDocument, BlogpostDocumentData, BlogpostDocumentDataSlicesSlice, BlogpostDocument, ContactpageDocumentData, ContactpageDocument, FaqpageDocumentData, FaqpageDocumentDataSlicesSlice, FaqpageDocument, TakeactionpageDocumentData, TakeactionpageDocumentDataSlices1Slice, TakeactionpageDocumentDataSlices2Slice, TakeactionpageDocumentDataSlices3Slice, TakeactionpageDocumentDataSlices4Slice, TakeactionpageDocument, AllDocumentTypes, AccordionSliceSliceRichTextPrimary, AccordionSliceSliceRichText, AccordionSliceSliceRichTextWithStepPrimary, AccordionSliceSliceRichTextWithStep, AccordionSliceSliceDefaultPrimary, AccordionSliceSliceDefault, AccordionSliceSliceVariation, AccordionSliceSlice, ButtonSliceSliceDefaultPrimary, ButtonSliceSliceDefault, ButtonSliceSliceVariation, ButtonSliceSlice, EmbedSliceSliceDefaultPrimary, EmbedSliceSliceDefault, EmbedSliceSliceVariation, EmbedSliceSlice, ImageSliceSliceDefaultPrimary, ImageSliceSliceDefault, ImageSliceSliceVariation, ImageSliceSlice, SharePicGallerySliceSliceDefault, SharePicGallerySliceSliceVariation, SharePicGallerySliceSlice, SocialSharerSliceSliceDefault, SocialSharerSliceSliceVariation, SocialSharerSliceSlice, TextSliceSliceDefaultPrimary, TextSliceSliceDefault, TextSliceSliceVariation, TextSliceSlice };
    }
}
