// Code generated by Slice Machine. DO NOT EDIT.

import EmbedBlock from './EmbedBlock';
import ImageBlock from './ImageBlock';
import TextBlock from './TextBlock';

export {
	EmbedBlock,
	ImageBlock,
	TextBlock,
};

export const components = {
	video_block: EmbedBlock,
	blog_image: ImageBlock,
	text_block: TextBlock,
};
