// Code generated by Slice Machine. DO NOT EDIT.

import EmbedSlice from './EmbedSlice';
import ImageSlice from './ImageSlice';
import TextSlice from './TextSlice';

export {
	EmbedSlice,
	ImageSlice,
	TextSlice,
};

export const components = {
	embed_slice: EmbedSlice,
	image_slice: ImageSlice,
	text_slice: TextSlice,
};
