// Code generated by Slice Machine. DO NOT EDIT.

import AccordionSlice from './AccordionSlice';
import ButtonSlice from './ButtonSlice';
import EmbedSlice from './EmbedSlice';
import ImageSlice from './ImageSlice';
import TextSlice from './TextSlice';

export {
	AccordionSlice,
	ButtonSlice,
	EmbedSlice,
	ImageSlice,
	TextSlice,
};

export const components = {
	accordion_slice: AccordionSlice,
	button_slice: ButtonSlice,
	embed_slice: EmbedSlice,
	image_slice: ImageSlice,
	text_slice: TextSlice,
};
